-- Create import function for main destinations
CREATE OR REPLACE FUNCTION public.school_import_ks4_destinations_main(destinations jsonb)
RETURNS jsonb AS $$
BEGIN
  INSERT INTO ks4_destinations_main (
    id,
    urn,
    year,
    sustained,
    education,
    employment,
    apprenticeships,
    further_education,
    sixth_form,
    sixth_form_college,
    disadvantaged_sustained,
    non_disadvantaged_sustained,
    cohort_size,
    last_updated
  )
  SELECT * FROM jsonb_to_recordset(destinations) AS x(
    id text,
    urn text,
    year text,
    sustained numeric,
    education numeric,
    employment numeric,
    apprenticeships numeric,
    further_education numeric,
    sixth_form numeric,
    sixth_form_college numeric,
    disadvantaged_sustained numeric,
    non_disadvantaged_sustained numeric,
    cohort_size numeric,
    last_updated timestamptz
  )
  ON CONFLICT (id) DO UPDATE SET
    urn = EXCLUDED.urn,
    year = EXCLUDED.year,
    sustained = EXCLUDED.sustained,
    education = EXCLUDED.education,
    employment = EXCLUDED.employment,
    apprenticeships = EXCLUDED.apprenticeships,
    further_education = EXCLUDED.further_education,
    sixth_form = EXCLUDED.sixth_form,
    sixth_form_college = EXCLUDED.sixth_form_college,
    disadvantaged_sustained = EXCLUDED.disadvantaged_sustained,
    non_disadvantaged_sustained = EXCLUDED.non_disadvantaged_sustained,
    cohort_size = EXCLUDED.cohort_size,
    last_updated = EXCLUDED.last_updated,
    updated_at = NOW();

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Create import function for stats
CREATE OR REPLACE FUNCTION public.school_import_ks4_destinations_details(details jsonb)
RETURNS jsonb AS $$
BEGIN
  INSERT INTO ks4_destinations_details (
    id,
    urn,
    year,
    -- Numbers section
    cohort_number,
    sustained_number,
    education_number,
    employment_number,
    apprenticeships_number,
    further_education_number,
    school_sixth_form_number,
    sixth_form_college_number,
    other_education_number,
    not_sustained_number,
    unknown_number,
    -- Disadvantaged section
    disadvantaged_cohort,
    disadvantaged_sustained_number,
    disadvantaged_sustained_percentage,
    disadvantaged_education_number,
    disadvantaged_education_percentage,
    disadvantaged_employment_number,
    disadvantaged_employment_percentage,
    disadvantaged_apprenticeships_number,
    disadvantaged_apprenticeships_percentage,
    disadvantaged_further_education_number,
    disadvantaged_further_education_percentage,
    disadvantaged_school_sixth_form_number,
    disadvantaged_school_sixth_form_percentage,
    disadvantaged_sixth_form_college_number,
    disadvantaged_sixth_form_college_percentage,
    disadvantaged_other_education_number,
    disadvantaged_other_education_percentage,
    disadvantaged_not_sustained_number,
    disadvantaged_not_sustained_percentage,
    disadvantaged_unknown_number,
    disadvantaged_unknown_percentage,
    -- Non-disadvantaged section
    non_disadvantaged_cohort,
    non_disadvantaged_sustained_number,
    non_disadvantaged_sustained_percentage,
    non_disadvantaged_education_number,
    non_disadvantaged_education_percentage,
    non_disadvantaged_employment_number,
    non_disadvantaged_employment_percentage,
    non_disadvantaged_apprenticeships_number,
    non_disadvantaged_apprenticeships_percentage,
    non_disadvantaged_further_education_number,
    non_disadvantaged_further_education_percentage,
    non_disadvantaged_school_sixth_form_number,
    non_disadvantaged_school_sixth_form_percentage,
    non_disadvantaged_sixth_form_college_number,
    non_disadvantaged_sixth_form_college_percentage,
    non_disadvantaged_other_education_number,
    non_disadvantaged_other_education_percentage,
    non_disadvantaged_not_sustained_number,
    non_disadvantaged_not_sustained_percentage,
    non_disadvantaged_unknown_number,
    non_disadvantaged_unknown_percentage,
    last_updated
  )
  SELECT * FROM jsonb_to_recordset(details) AS x(
    id text,
    urn text,
    year text,
    -- Numbers section
    cohort_number numeric,
    sustained_number numeric,
    education_number numeric,
    employment_number numeric,
    apprenticeships_number numeric,
    further_education_number numeric,
    school_sixth_form_number numeric,
    sixth_form_college_number numeric,
    other_education_number numeric,
    not_sustained_number numeric,
    unknown_number numeric,
    -- Disadvantaged section
    disadvantaged_cohort numeric,
    disadvantaged_sustained_number numeric,
    disadvantaged_sustained_percentage numeric,
    disadvantaged_education_number numeric,
    disadvantaged_education_percentage numeric,
    disadvantaged_employment_number numeric,
    disadvantaged_employment_percentage numeric,
    disadvantaged_apprenticeships_number numeric,
    disadvantaged_apprenticeships_percentage numeric,
    disadvantaged_further_education_number numeric,
    disadvantaged_further_education_percentage numeric,
    disadvantaged_school_sixth_form_number numeric,
    disadvantaged_school_sixth_form_percentage numeric,
    disadvantaged_sixth_form_college_number numeric,
    disadvantaged_sixth_form_college_percentage numeric,
    disadvantaged_other_education_number numeric,
    disadvantaged_other_education_percentage numeric,
    disadvantaged_not_sustained_number numeric,
    disadvantaged_not_sustained_percentage numeric,
    disadvantaged_unknown_number numeric,
    disadvantaged_unknown_percentage numeric,
    -- Non-disadvantaged section
    non_disadvantaged_cohort numeric,
    non_disadvantaged_sustained_number numeric,
    non_disadvantaged_sustained_percentage numeric,
    non_disadvantaged_education_number numeric,
    non_disadvantaged_education_percentage numeric,
    non_disadvantaged_employment_number numeric,
    non_disadvantaged_employment_percentage numeric,
    non_disadvantaged_apprenticeships_number numeric,
    non_disadvantaged_apprenticeships_percentage numeric,
    non_disadvantaged_further_education_number numeric,
    non_disadvantaged_further_education_percentage numeric,
    non_disadvantaged_school_sixth_form_number numeric,
    non_disadvantaged_school_sixth_form_percentage numeric,
    non_disadvantaged_sixth_form_college_number numeric,
    non_disadvantaged_sixth_form_college_percentage numeric,
    non_disadvantaged_other_education_number numeric,
    non_disadvantaged_other_education_percentage numeric,
    non_disadvantaged_not_sustained_number numeric,
    non_disadvantaged_not_sustained_percentage numeric,
    non_disadvantaged_unknown_number numeric,
    non_disadvantaged_unknown_percentage numeric,
    last_updated timestamptz
  )
  ON CONFLICT (id) DO UPDATE SET
    urn = EXCLUDED.urn,
    year = EXCLUDED.year,
    cohort_number = EXCLUDED.cohort_number,
    sustained_number = EXCLUDED.sustained_number,
    education_number = EXCLUDED.education_number,
    employment_number = EXCLUDED.employment_number,
    apprenticeships_number = EXCLUDED.apprenticeships_number,
    further_education_number = EXCLUDED.further_education_number,
    school_sixth_form_number = EXCLUDED.school_sixth_form_number,
    sixth_form_college_number = EXCLUDED.sixth_form_college_number,
    other_education_number = EXCLUDED.other_education_number,
    not_sustained_number = EXCLUDED.not_sustained_number,
    unknown_number = EXCLUDED.unknown_number,
    disadvantaged_cohort = EXCLUDED.disadvantaged_cohort,
    disadvantaged_sustained_number = EXCLUDED.disadvantaged_sustained_number,
    disadvantaged_sustained_percentage = EXCLUDED.disadvantaged_sustained_percentage,
    disadvantaged_education_number = EXCLUDED.disadvantaged_education_number,
    disadvantaged_education_percentage = EXCLUDED.disadvantaged_education_percentage,
    disadvantaged_employment_number = EXCLUDED.disadvantaged_employment_number,
    disadvantaged_employment_percentage = EXCLUDED.disadvantaged_employment_percentage,
    disadvantaged_apprenticeships_number = EXCLUDED.disadvantaged_apprenticeships_number,
    disadvantaged_apprenticeships_percentage = EXCLUDED.disadvantaged_apprenticeships_percentage,
    disadvantaged_further_education_number = EXCLUDED.disadvantaged_further_education_number,
    disadvantaged_further_education_percentage = EXCLUDED.disadvantaged_further_education_percentage,
    disadvantaged_school_sixth_form_number = EXCLUDED.disadvantaged_school_sixth_form_number,
    disadvantaged_school_sixth_form_percentage = EXCLUDED.disadvantaged_school_sixth_form_percentage,
    disadvantaged_sixth_form_college_number = EXCLUDED.disadvantaged_sixth_form_college_number,
    disadvantaged_sixth_form_college_percentage = EXCLUDED.disadvantaged_sixth_form_college_percentage,
    disadvantaged_other_education_number = EXCLUDED.disadvantaged_other_education_number,
    disadvantaged_other_education_percentage = EXCLUDED.disadvantaged_other_education_percentage,
    disadvantaged_not_sustained_number = EXCLUDED.disadvantaged_not_sustained_number,
    disadvantaged_not_sustained_percentage = EXCLUDED.disadvantaged_not_sustained_percentage,
    disadvantaged_unknown_number = EXCLUDED.disadvantaged_unknown_number,
    disadvantaged_unknown_percentage = EXCLUDED.disadvantaged_unknown_percentage,
    non_disadvantaged_cohort = EXCLUDED.non_disadvantaged_cohort,
    non_disadvantaged_sustained_number = EXCLUDED.non_disadvantaged_sustained_number,
    non_disadvantaged_sustained_percentage = EXCLUDED.non_disadvantaged_sustained_percentage,
    non_disadvantaged_education_number = EXCLUDED.non_disadvantaged_education_number,
    non_disadvantaged_education_percentage = EXCLUDED.non_disadvantaged_education_percentage,
    non_disadvantaged_employment_number = EXCLUDED.non_disadvantaged_employment_number,
    non_disadvantaged_employment_percentage = EXCLUDED.non_disadvantaged_employment_percentage,
    non_disadvantaged_apprenticeships_number = EXCLUDED.non_disadvantaged_apprenticeships_number,
    non_disadvantaged_apprenticeships_percentage = EXCLUDED.non_disadvantaged_apprenticeships_percentage,
    non_disadvantaged_further_education_number = EXCLUDED.non_disadvantaged_further_education_number,
    non_disadvantaged_further_education_percentage = EXCLUDED.non_disadvantaged_further_education_percentage,
    non_disadvantaged_school_sixth_form_number = EXCLUDED.non_disadvantaged_school_sixth_form_number,
    non_disadvantaged_school_sixth_form_percentage = EXCLUDED.non_disadvantaged_school_sixth_form_percentage,
    non_disadvantaged_sixth_form_college_number = EXCLUDED.non_disadvantaged_sixth_form_college_number,
    non_disadvantaged_sixth_form_college_percentage = EXCLUDED.non_disadvantaged_sixth_form_college_percentage,
    non_disadvantaged_other_education_number = EXCLUDED.non_disadvantaged_other_education_number,
    non_disadvantaged_other_education_percentage = EXCLUDED.non_disadvantaged_other_education_percentage,
    non_disadvantaged_not_sustained_number = EXCLUDED.non_disadvantaged_not_sustained_number,
    non_disadvantaged_not_sustained_percentage = EXCLUDED.non_disadvantaged_not_sustained_percentage,
    non_disadvantaged_unknown_number = EXCLUDED.non_disadvantaged_unknown_number,
    non_disadvantaged_unknown_percentage = EXCLUDED.non_disadvantaged_unknown_percentage,
    last_updated = EXCLUDED.last_updated,
    updated_at = NOW();

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;