import './global.css';

export const metadata = {
  title: 'Welcome to uk-schools-finder',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <main className="container mx-auto h-screen max-w-none px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
